//
// Created by miska on 10/10/2024.
//

#include "TextureAddressMode.h"

const TextureAddressMode TextureAddressMode::REPEAT = {
    VK_SAMPLER_ADDRESS_MODE_REPEAT, VK_SAMPLER_ADDRESS_MODE_REPEAT, VK_SAMPLER_ADDRESS_MODE_REPEAT
};


const TextureAddressMode TextureAddressMode::CLAMP_TO_BORDER = {
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
};

const TextureAddressMode TextureAddressMode::CLAMP_TO_EDGE = {
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE
};

const TextureAddressMode TextureAddressMode::MIRRORED_REPEAT = {
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT, VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT
};

const TextureAddressMode TextureAddressMode::MIRROR_CLAMP_TO_EDGE = {
    VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE, VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE,
    VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE
};
